custom_categories:
  - name: Getting Started 
    children:
    - ReactivePrimitives
    - BasicOperators
    - Example.OnlineSearch
    - RxComparison
  - name: Advanced Topics
    children:
    - APIContracts
    - DebuggingTechniques
  - name: Signal
    children:
    - Signal
    - SignalProtocol
    - FlattenStrategy
  - name: SignalProducer
    children:
    - SignalProducer
    - SignalProducerProtocol
  - name: Property
    children:
    - Property
    - PropertyProtocol
    - MutableProperty
    - MutablePropertyProtocol
    - ValidatingProperty
  - name: Action
    children:
    - Action
    - ActionError
  - name: Bindings
    children:
    - BindingSource
    - BindingTarget
    - BindingTargetProvider
  - name: Scheduler Protocols
    children:
    - DateScheduler
    - Scheduler
  - name: Schedulers
    children:
    - ImmediateScheduler
    - QueueScheduler
    - TestScheduler
    - UIScheduler
  - name: Reactive Extensions
    children:
    - Reactive
    - ReactiveExtensionsProvider
  - name: Lifetime
    children:
    - Lifetime
  - name: Disposable
    children:
    - AnyDisposable
    - ActionDisposable    
    - Disposable
    - CompositeDisposable
    - ScopedDisposable 
    - SerialDisposable
    - SimpleDisposable
    - +=(_:_:)
  - name: Debugging
    children:
    - EventLogger
    - LoggingEvent
  - name: Utilities 
    children:
    - Atomic
    - Bag
    - Optional
    - OptionalProtocol
theme: fullwidth 
skip_undocumented: true
readme: README.md
documentation: Documentation/*.md
hide_documentation_coverage: true
xcodebuild_arguments:
  - -workspace
  - ReactiveSwift.xcworkspace
  - -scheme
  - ReactiveSwift-macOS
author: ReactiveCocoa
author_url: https://reactivecocoa.io/
github_url: https://github.com/ReactiveCocoa/ReactiveSwift/
dash_url: http://reactivecocoa.io/reactiveswift/docs/ReactiveSwift.xml
